apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog2-xpo7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog2-xpo7
    app.kubernetes.io/part-of: my-app-2
  name: partner-catalog2-xpo7
  namespace: mreid-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: partner-catalog2-xpo7
status:
  loadBalancer: {}
